/** Shared content — copy & data only (from design handoff `content.jsx`). */
export const SITE = {
  name: 'Little Compasses',
  tagline: 'Licensed family dayhome in Livingston NW Calgary',
  hero: {
    headline: 'A soft place\nto be little.',
    h1Seo: 'Licensed Dayhome in Livingston NW Calgary | Little Prairie',
    sub: 'Approved family dayhome serving Livingston, Carrington, Evanston, Ambleton, Sage Hill, Panorama Hills & Coventry Hills.',
    cta: 'Book a tour',
    cta2: 'Join the waitlist',
  },
  trustBadges: [
    { label: 'Licensed under Alberta ELCC Act', icon: 'shield' },
    { label: 'First Aid + CPR-C', icon: 'heart' },
    { label: 'Police + Vulnerable Sector + Child Intervention', icon: 'badge' },
  ],
  neighbourhoods: ['Livingston', 'Carrington', 'Evanston', 'Ambleton', 'Sage Hill', 'Panorama Hills', 'Coventry Hills'],
  about: {
    name: "Hi, I'm Zakiyah",
    role: 'Licensed Educator · Owner',
    eceLevel: 'ECE Level 3 (Early Childhood Development Supervisor)',
    yearsExperience: '9 years caring for children in Calgary',
    languages: ['English', 'Hindi', 'Punjabi', 'Urdu'],
    body: "I've looked after little ones in Calgary for nine years — three of them right here in my Livingston home. I have an Early Learning & Child Care diploma from Bow Valley College and have completed the full Alberta Child Care Certification pathway to Level 3.",
    philosophy: '“Children learn the world by tasting it, climbing it, and asking it endless questions. My job is to keep the world safe enough that they can.”',
    family: '',
    certifications: [
      'ELCC Diploma · Bow Valley College',
      'Alberta Child Care Certification — Level 3',
      'Standard First Aid + CPR-C (current)',
      'Food Safety Basics — Alberta Health Services',
      'Health & Safety Basics for Childcare Providers',
      'Police Information Check + Vulnerable Sector',
      'Child Intervention Record Check',
    ],
  },
  schedule: [
    { time: '7:00', label: 'Doors open', note: 'soft arrivals + free play' },
    { time: '8:30', label: 'Family breakfast', note: 'always something warm' },
    { time: '9:15', label: 'Circle + story', note: 'songs in English, Hindi, Punjabi & Urdu' },
    { time: '9:45', label: 'Outside time', note: 'Nose Creek pathway / Livingston parks' },
    { time: '11:30', label: 'Lunch together', note: 'home-cooked, family-style' },
    { time: '12:30', label: 'Quiet rest', note: 'cots, lullabies, glow stars' },
    { time: '14:30', label: 'Snack + project', note: 'craft, water table, baking' },
    { time: '15:30', label: 'Outside again', note: 'or messy play if it\'s a -30 day' },
    { time: '16:30', label: 'Wind-down', note: 'puzzles + parent pickup' },
    { time: '17:30', label: 'Doors close', note: 'see you tomorrow!' },
  ],
  programs: [
    { title: 'Tiny Tinkerers', age: '0–18 mo', desc: 'Sensory baskets, tummy time, quiet cuddles, and lots of one-on-one.', icon: 'Heart' },
    { title: 'Wobbly Walkers', age: '18 mo–3 yr', desc: 'First friendships, first words, first muddy boots.', icon: 'Blocks' },
    { title: 'Big Adventurers', age: '3–5 yr', desc: 'Letters, numbers, weather watching, and very serious science.', icon: 'Star' },
  ],
  curriculum: {
    framework: 'Alberta Flight Framework',
    frameworkUrl: 'https://flightframework.ca',
    intro: 'Our daily program is built around Flight: Alberta\'s Early Learning & Care Framework — the four play-based dispositions of well-being, play & playfulness, communication & literacies, and diversity & social responsibility.',
    pillars: [
      { title: 'Well-being', desc: 'Children feel safe, fed, rested and seen. Predictable rhythms, gentle transitions.' },
      { title: 'Play & playfulness', desc: 'Loose-parts, mud kitchen, dramatic play. Long uninterrupted blocks of self-directed play.' },
      { title: 'Communication & literacies', desc: 'Daily story circle, songs, mark-making, conversations during meals.' },
      { title: 'Diversity & social responsibility', desc: 'Treaty 7 land acknowledgement, books reflecting our families, Hindi, Punjabi & Urdu alongside English.' },
    ],
    structure: [
      { count: '6', label: 'children max' },
      { count: 'mixed', label: 'ages 0–5' },
      { count: '1:6', label: 'educator ratio' },
      { count: 'no', label: 'screens policy' },
    ],
  },
  meals: {
    intro: 'Three home-cooked meals a day, plus two snacks. Marco plans the menu on Sundays following the Canada Food Guide and we shop at the Crossroads Market.',
    sample: [
      { day: 'Monday', breakfast: 'Steel-cut oats, berries', lunch: 'Lentil dahl, brown rice, naan', snack: 'Apple, sunflower butter' },
      { day: 'Tuesday', breakfast: 'Whole-grain pancakes', lunch: 'Chicken & barley soup, bun', snack: 'Cheese, cucumber, oat crackers' },
      { day: 'Wednesday', breakfast: 'Yogurt parfait', lunch: 'Veggie chili, cornbread', snack: 'Banana muffins' },
      { day: 'Thursday', breakfast: 'Scrambled eggs, toast', lunch: 'Pasta marinara, peas', snack: 'Hummus, pita, carrots' },
      { day: 'Friday', breakfast: 'Overnight oats', lunch: 'Halal chicken curry, rice', snack: 'Pear slices, cheddar' },
    ],
    notes: 'Nut-free kitchen. Halal and vegetarian options always available. We accommodate dairy, gluten, and any documented allergy.',
  },
  outdoor: {
    intro: 'Outside every day — yes, even at -20°. We have full snowsuits on hand and a backup plan for -30.',
    spots: [
      { name: 'Livingston Hub', desc: 'splash pad in summer, sledding hill in winter' },
      { name: 'Nose Creek pathway', desc: 'duck-watching, frozen-puddle physics' },
      { name: 'Carrington Pond', desc: 'wide open green space, monthly walks' },
      { name: 'Backyard', desc: 'mud kitchen, sandbox, raised veggie beds' },
    ],
  },
  rates: {
    headline: 'Plain & simple pricing',
    sub: 'Transparent monthly rates for Livingston families. Full details shared at your tour.',
    rows: [
      { age: 'Full-time (5 days)', price: '$326.25 / mo' },
      { age: 'Part-time (3 days)', price: '$230.00 / mo' },
      { age: 'One-time registration', price: '$95 (one-time)' },
    ],
    optional: [
      { item: 'Late pickup (after 5:30 pm)', cost: '$1/min' },
      { item: 'Field-trip materials fund', cost: '$10/mo (optional)' },
    ],
    foot: 'All rates include three home-cooked meals, two snacks, diapers (infants), field trips, art supplies & sunscreen. No registration deposit until your spot is confirmed.',
  },
  testimonials: [
    { quote: 'Zakiyah is the reason our daughter says "outside please" before she says hello. She comes home tired, muddy, and so happy.', who: 'Priya & Dev', child: 'parents of Anika, 2' },
    { quote: 'We toured eight dayhomes in the NW. This one had a kid up to her elbows in flour making "bird bread." We signed the next day.', who: 'The Nguyens', child: 'parents of Kai, 4' },
    { quote: 'Our son was so shy. Six weeks later he was leading the morning song. The transition support was unreal.', who: 'Hannah M.', child: 'mom of Theo, 3' },
  ],
  faq: [
    { q: 'What are your hours?', a: 'Monday–Friday, 7:00 am–5:30 pm. Closed weekends and all Alberta statutory holidays (New Year\'s, Family Day, Good Friday, Victoria Day, Canada Day, Heritage Day, Labour Day, Thanksgiving, Remembrance Day, Christmas Day, Boxing Day). A full closure calendar is shared at enrollment.' },
    { q: 'Are you licensed?', a: 'Yes — licensed family day home regulated under Alberta\'s Family Day Home Standards (ELCC Act). Inspections are on file and shared with families.' },
    { q: 'What\'s your sick child policy?', a: 'Children stay home with: fever ≥38°C, vomiting/diarrhea in the last 24 hours, undiagnosed rash, conjunctivitis, or any communicable illness. Return after 24 hours symptom-free without medication. We never charge for child sick days.' },
    { q: 'How many kids are here total?', a: 'Six children max. Usually two infants, two toddlers, two preschoolers — a true mixed-age family. Educator ratio 1:6 as per Alberta standards.' },
    { q: 'What should we bring on the first day?', a: 'Indoor shoes, full change of clothes (×2), labelled water bottle, a comfort item for nap, weather-appropriate outdoor gear, and any remaining enrollment forms. Diapers and meals are provided.' },
    { q: 'What if my child has allergies?', a: 'Our kitchen is fully nut-free. We accommodate dairy, gluten, halal, vegetarian, and any documented allergy. EpiPens are stored per Alberta med-storage protocol and all educators are trained on administration.' },
    { q: 'Can I drop in to visit?', a: 'After enrollment, anytime. Before enrollment, we run 20-minute tours Tuesdays & Thursdays at 1 pm during nap so you actually see the space. Book a slot below.' },
  ],
  tour: {
    intro: 'Tours are 20 minutes, Tuesdays and Thursdays at 1 pm during nap so you can see the full space.',
    process: [
      { step: '1', label: 'Book a slot', desc: 'Pick a 20-minute Tues or Thurs at 1 pm.' },
      { step: '2', label: 'Walk the space', desc: 'Play room, nap room, kitchen, fenced yard.' },
      { step: '3', label: 'Meet Zakiyah', desc: 'Bring your questions — and your kid if you like.' },
      { step: '4', label: 'Get the paperwork', desc: 'Sample forms and enrollment info to take home.' },
    ],
  },
  contact: {
    address: 'Livingston Drive NW · Calgary, AB',
    community: 'Livingston, Calgary',
    phone: '587-917-5106',
    phoneTel: '+15879175106',
    email: 'hello@littleprairie.ca',
    hours: 'Mon–Fri · 7:00 am – 5:30 pm',
  },
  gallery: [
    'mud kitchen morning',
    'circle time songs',
    'first-snow eyebrows',
    'pumpkin painting',
    'reading nook',
    'backyard tomatoes',
  ],
};
