/** Soft Cloud direction — five selectable palettes (from `direction-4-soft-cloud.jsx`). */
export const SOFT_CLOUD_THEMES = {
  peachBlossom: {
    name: 'Peach Blossom',
    desc: 'The original — warm peach, lilac, butter, cream',
    bg: '#fef5ee',
    paper: '#fffbf5',
    ink: '#3d2e3a',
    inkSoft: '#7d6976',
    accent: '#e8a0a0',
    accent2: '#c0a4d4',
    accent3: '#f5d088',
    accent4: '#a4c8d4',
    trunk: '#a08070',
    leaf: '#a8c4a4',
    cheek: '#f0b8b8',
  },
  morningMist: {
    name: 'Morning Mist',
    desc: 'Cool sage, dusty blue, soft cream — calm and airy',
    bg: '#f0f4ee',
    paper: '#fbfcf8',
    ink: '#2d3a36',
    inkSoft: '#6a786f',
    accent: '#8eb89c',
    accent2: '#a8c0d4',
    accent3: '#e8d8a4',
    accent4: '#d4b8c8',
    trunk: '#9a8a78',
    leaf: '#8eb89c',
    cheek: '#e0c8b4',
  },
  lavenderHaze: {
    name: 'Lavender Haze',
    desc: 'Lilac forward, soft rose, butter — gentle dusk',
    bg: '#f3eef5',
    paper: '#fbf8fc',
    ink: '#3a2e44',
    inkSoft: '#766a82',
    accent: '#b094c8',
    accent2: '#e0a8b8',
    accent3: '#f0d098',
    accent4: '#a8c8c0',
    trunk: '#9080a0',
    leaf: '#a8c4b4',
    cheek: '#e8b8c4',
  },
  butterCreamery: {
    name: 'Butter Creamery',
    desc: 'Sunshiny butter, terracotta, sage — buttery & warm',
    bg: '#fef3d8',
    paper: '#fffbed',
    ink: '#3a2e1a',
    inkSoft: '#7a6a4a',
    accent: '#e89870',
    accent2: '#9ab87a',
    accent3: '#f0c860',
    accent4: '#d4a8a0',
    trunk: '#a08050',
    leaf: '#9ab87a',
    cheek: '#f0b890',
  },
  oceanNursery: {
    name: 'Ocean Nursery',
    desc: 'Powder blue, mint, coral, cream — sea-glass calm',
    bg: '#eef4f5',
    paper: '#fafdfd',
    ink: '#2a3a44',
    inkSoft: '#5a7080',
    accent: '#f0a48a',
    accent2: '#7eb0c0',
    accent3: '#f5d890',
    accent4: '#9ec8b8',
    trunk: '#8a907a',
    leaf: '#9ec8b8',
    cheek: '#f0b8a0',
  },
};
